config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/oidc-agent:
      branch: prerel
      repo: https://github.com/indigo-dc/oidc-agent
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/oidc-agent git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-pink-angelfish.sh
        container: qc.acc_geeky-fuchsia-pinscher
  QC.Doc:
    repos:
      github.com/indigo-dc/oidc-agent find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-copper-guppy.sh
        container: qc.doc_shaggy-salmon-turtle
      github.com/indigo-dc/oidc-agent git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-amethyst-bombay.sh
        container: qc.doc_woozy-cerulean-woodlouse
      github.com/indigo-dc/oidc-agent markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cyan-clam.sh
        container: qc.doc_hazy-ochre-indri
  QC.Lic:
    repos:
      github.com/indigo-dc/oidc-agent licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-plum-shrimp.sh
        container: qc.lic_freaky-tomato-mist
  QC.Sec:
    repos:
      github.com/indigo-dc/oidc-agent bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-jade-rhinoceros.sh
        container: qc.sec_hasty-alizarin-lionfish
  QC.Sty:
    repos:
      github.com/indigo-dc/oidc-agent flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cerulean-eel.sh
        container: qc.sty_flabby-beige-weasel
      github.com/indigo-dc/oidc-agent jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-green-bulldog.sh
        container: qc.sty_sleazy-cobalt-capybara
  QC.Ver:
    repos:
      github.com/indigo-dc/oidc-agent get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-blue-wombat.sh
        container: qc.ver_squeaky-mauve-snake
timeout: 5400
